### PR TITLE
Fix incorrect wikidata id

### PR DESCRIPTION
**Pull request by schmidek**

### CODE REVIEW

**Comment by stepps00** [comment]
Thanks for the PR, @schmidek 

It looks like there are non-English names being added to the English label and name properties - do you know which language the new label value is in?

I agree with the concordance change, and there are additional name changes needed. Once we get the label value sorted, we can update more names and merge this PR.

**Comment by stepps00** [comment]
I'm only seeing notifications now, strangely - apologies for the (very) long delay here.

**Comment by schmidek** [comment]
The previous `label:eng_x_preferred_longname` was in Bulgarian, so I fixed it to be English.

**Comment by stepps00** [comment]
I'm going to close this PR, I've moved your commit to https://github.com/whosonfirst-data/whosonfirst-data-admin-bg/pull/18 so the changes can be merged. Thanks @schmidek

**Pull request closed without merging**
